# openssl rand -hex 64 생성
jwt:
  secret-key: fde99ec721a71aba1c24577d6d47e4d149c5c48d2d143e96ad9e25953d4bf7a48f9404f0a27e0067d13809d496f72a56d98bf611c7a36b0b878b63dae651bd85
  access-expiration-seconds: 120 # 엑세스 토큰 만료시간(초)
  refresh-expiration-seconds: 180 # 리프래쉬 토큰 만료시간(초)

logging:
  level:
    org.springframework.security: debug